"""Unit tests for the mock Enterprise Vault generators and loader."""

from __future__ import annotations

import hashlib

from mock_ev.entities import VaultStore
from mock_ev.generators import (
    LARGE_PROFILE,
    MEDIUM_PROFILE,
    SMALL_PROFILE,
    ArchiveGenerator,
    AttachmentGenerator,
    DatasetGenerator,
    FixtureLoader,
    MailboxGenerator,
    MailGenerator,
)
from mock_ev.loaders import DepartmentFixture, RetentionPolicyFixture, UserFixture


def _count_archives(dataset: list[VaultStore]) -> int:
    return sum(len(vault_store.archives) for vault_store in dataset)


def _count_mailboxes(dataset: list[VaultStore]) -> int:
    return sum(
        len(archive.mailboxes) for vault_store in dataset for archive in vault_store.archives
    )


def _count_mail_items(dataset: list[VaultStore]) -> int:
    return sum(
        len(mailbox.mail_items)
        for vault_store in dataset
        for archive in vault_store.archives
        for mailbox in archive.mailboxes
    )


def _count_attachments(dataset: list[VaultStore]) -> int:
    return sum(
        len(mail_item.attachments)
        for vault_store in dataset
        for archive in vault_store.archives
        for mailbox in archive.mailboxes
        for mail_item in mailbox.mail_items
    )


def test_fixture_loader_reads_expected_files() -> None:
    """The fixture loader should expose the expected typed fixture payloads."""

    loader = FixtureLoader()

    users = loader.load_users()
    departments = loader.load_departments()
    retention_policies = loader.load_retention_policies()
    mail_subjects = loader.load_mail_subjects()
    attachment_names = loader.load_attachment_names()

    assert isinstance(users[0], UserFixture)
    assert isinstance(departments[0], DepartmentFixture)
    assert isinstance(retention_policies[0], RetentionPolicyFixture)
    assert users[0].id == "user-001"
    assert departments[0].name == "Finance"
    assert retention_policies[1].classification == "regulated"
    assert mail_subjects[0] == "Quarterly financial review"
    assert attachment_names[0] == "invoice.pdf"


def test_dataset_generator_is_deterministic_for_same_seed() -> None:
    """The same seed should produce identical datasets."""

    generator_a = DatasetGenerator(seed=42)
    generator_b = DatasetGenerator(seed=42)

    dataset_a = generator_a.generate_small()
    dataset_b = generator_b.generate_small()

    assert dataset_a == dataset_b


def test_dataset_generator_differs_for_different_seeds() -> None:
    """Different seeds should produce different synthetic datasets."""

    dataset_a = DatasetGenerator(seed=1).generate_small()
    dataset_b = DatasetGenerator(seed=2).generate_small()

    assert dataset_a != dataset_b


def test_small_profile_sizes_are_correct() -> None:
    """The small profile should match the expected entity counts."""

    dataset = DatasetGenerator(seed=7).generate_small()

    assert len(dataset) == SMALL_PROFILE.vault_stores
    assert _count_archives(dataset) == SMALL_PROFILE.archives
    assert _count_mailboxes(dataset) == SMALL_PROFILE.mailboxes
    assert _count_mail_items(dataset) == SMALL_PROFILE.mail_items
    assert _count_attachments(dataset) == SMALL_PROFILE.attachments


def test_dataset_profiles_are_defined() -> None:
    """The predefined dataset profiles should expose the expected constants."""

    assert MEDIUM_PROFILE.vault_stores == 5
    assert LARGE_PROFILE.mail_items == 100_000


def test_attachment_generator_creates_sha256_checksums() -> None:
    """Attachments generated by the attachment generator should carry SHA-256 checksums."""

    generator = AttachmentGenerator(seed=3)
    attachment = generator.generate_one(
        filename="report.pdf",
        mime_type="application/pdf",
        size_bytes=128,
    )

    checksum = hashlib.sha256(b"report.pdf|pdf|application/pdf|128").hexdigest()

    assert attachment.filename == "report.pdf"
    assert attachment.extension == "pdf"
    assert attachment.mime_type == "application/pdf"
    assert attachment.size_bytes == 128
    assert attachment.checksum == checksum


def test_mail_generator_creates_complete_mail_items() -> None:
    """The mail generator should create realistic mail items with attachments."""

    mail_item = MailGenerator(seed=5).generate_one(attachment_count=2)

    assert mail_item.sender
    assert mail_item.subject
    assert mail_item.body
    assert mail_item.received_at <= mail_item.modified_at
    assert mail_item.sent_at <= mail_item.received_at
    assert len(mail_item.attachments) == 2
    assert len(mail_item.content_parts) == 1
    assert mail_item.content_parts[0].size_bytes == len(mail_item.body.encode("utf-8"))
    assert mail_item.retention_policy.name


def test_mailbox_and_archive_generators_build_nested_hierarchies() -> None:
    """Mailbox and archive generators should compose nested entities correctly."""

    mailbox = MailboxGenerator(seed=11).generate_one(attachment_counts=(2, 3))
    archive = ArchiveGenerator(seed=11).generate_one(
        mailbox_attachment_counts=((2, 3), (2, 2)),
    )

    assert len(mailbox.mail_items) == 2
    assert len(mailbox.mail_items[0].attachments) == 2
    assert len(mailbox.mail_items[1].attachments) == 3
    assert len(archive.mailboxes) == 2
    assert len(archive.mailboxes[0].mail_items) == 2
    assert len(archive.mailboxes[1].mail_items) == 2
